const Constants = {
    PUBKEY0_WIN: 'PUBKEY0_WIN',
    PUBKEY1_WIN: 'PUBKEY1_WIN',
    ONGOING: 'ONGOING',
    TIE: 'TIE',
    GAME_ID_NOT_EXIST: 'GAME_ID_NOT_EXIST',
    INVALID_MOVE: 'INVALID_MOVE',
    GAME_ALREADY_DONE: 'GAME_ALREADY_DONE',
    INVALID_OCCUPIED: 'INVALID_OCCUPIED',
    INVALID_NOT_YOUR_TURN: 'INVALID_NOT_YOUR_TURN',
    NEED_DIFF_PUBKEY: 'NEED_DIFF_PUBKEY',
    GAME_NOT_STARTED: 'GAME_NOT_STARTED',
    NOT_YOUR_GAME: 'NOT_YOUR_GAME',
    GAMER_TO_SIGNER: 'GAMER_TO_SIGNER',
};

module.exports = Constants;